export const GET_LIST_MOVIE_REQUEST = "GET_LIST_MOVIE_REQUEST"
export const GET_LIST_MOVIE_SUCCESS = " GET_LIST_MOVIE_SUCCESS"

export const GET_DETAIL_MOVIE_REQUEST = "GET_DETAIL_MOVIE_REQUEST"
export const GET_DETAIL_MOVIE_SUCCESS = "GET_DETAIL_MOVIE_SUCCESS"

export const SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST"
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS"

export const GET_MORE_MOVIE_REQUEST = "GET_MORE_MOVIE_REQUEST"
export const GET_MORE_MOVIE_SUCCESS = " GET_MORE_MOVIE_SUCCESS"

